All new makemodels script.

diff --git a/Onboard/pypredict/tools/makemodels b/Onboard/pypredict/tools/makemodels
--- a/Onboard/pypredict/tools/makemodels
+++ b/Onboard/pypredict/tools/makemodels
@@ -1,53 +1,45 @@
 #!/bin/bash
-# This program is free software: you can redistribute it and/or modify
+# Copyright © 2012, marmuta
+#
+# This file is part of Onboard.
+#
+# Onboard is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
-# the Free Software Foundation, either version 3 of the License, or
+# the Free Software Foundation; either version 3 of the License, or
 # (at your option) any later version.
 #
-# This program is distributed in the hope that it will be useful,
+# Onboard is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 # GNU General Public License for more details.
 #
 # You should have received a copy of the GNU General Public License
-# along with this program.  If not, see <http://www.gnu.org/licenses/>.
+# along with this program. If not, see <http://www.gnu.org/licenses/>.
 #
-# Author: marmuta <marmvta@gmail.com>
+# Important directories:
 #
+# ./models/raw    - Input directory containing large raw models with only
+#                   minimal processing (utf-8 encoded). Due to their large 
+#                   size, often in the GB range, raw models aren't
+#                   included with Onboard's source package, 
 #
-# Script to create language models
-# --------------------------------
-#
-# The languages for which dictionaries are built are determined
-# by the installed languages for the aspell spell checker.
-# In order to get additional or different language models, install
-# the appropriate language packages for aspell and re-run this
-# script. Aspell is only needed for dictionary creation, not
-# when running the word prediction service.
-#
-# Running the script the first time creates and populates
-# two directories:
-#
-# ./corpora       - Contains training texts by language.
-#                   It is only used during dictionary-creation and
-#                   if non-existant or deleted its content
-#                   will be recreated.
-#                   Training texts are mainly downloaded from
-#                   Project Gutenberg, http://www.gutenberg.org.
-#
-# ./models        - Holds system language models in utf-8 encoding
-#
+# ./models        - Output directory for final filtered system language models
+#                   (utf-8 encoded).
 #
 
+LANGUAGES="en_US en_GB de_DE"
+
 MODELDIR="models"
+RAWMODELDIR="../training/raw_models"
 MODELEXT="lm"
-TRAININGDIR="corpora"
+
 TRAIN_CMD=Onboard/pypredict/tools/train
-LANGUAGES=$(aspell dump dicts | grep -E "^[[:alpha:]_]*$" | sort | uniq)
-ORDER=3
+FILTER_CMD=Onboard/pypredict/tools/filter
+
+ORDER=2
 VERBOSE=0
-#MAX_UNIGRAMS=10000  # Allow this many unigrams; prunes all levels of n-grams.
-MAX_UNIGRAMS=0  # Allow this many unigrams; prunes all levels of n-grams.
+
+set -e
 
 help()
 {
@@ -55,7 +47,6 @@ cat >&2 << END
 Usage: `basename $0` [-e|E] [-i|I] [-v] [languages...]
 Script to create language models.
 Options:
- -o  Order of the language models to be created, default 3.
  -v  More verbose output
 
  -h  Show this help.
@@ -64,11 +55,8 @@ END
 
 
 # process command line arguments
-while getopts "o:v" opt; do
+while getopts "v" opt; do
 	case "$opt" in
-	o)
-		ORDER="$OPTARG"
-		;;
 	v)
 		VERBOSE=1
 		;;
@@ -87,24 +75,48 @@ shift $(($OPTIND - 1))
 # make sure the directories exist
 [ -d "$MODELDIR" ] || mkdir $MODELDIR
 
-# create language models
+# filter language models
 for lang in $LANGUAGES; do
-    MODELFILE="$MODELDIR/$lang.$MODELEXT"
+    lang_id=${lang:0:2}
+    MODEL_IN="$RAWMODELDIR/$lang_id.$MODELEXT.sorted-pruned"
+    MODEL_OUT="$MODELDIR/$lang.$MODELEXT"
 
-    echo "Building '$MODELFILE'..."
+    echo "Building '$MODEL_OUT'..."
 
-    # find training texts
-    if [ ${#lang} == 2 ]; then
-        LANGDIRS="$TRAININGDIR/${lang}*"
-    else
-        LANGDIRS="$TRAININGDIR/${lang::2},$TRAININGDIR/${lang}"
-    fi
-    echo "  Looking for training texts in:" $LANGDIRS
-    #TRAININGFILES=$(find ${LANGDIRS} -name "*.txt" -o -name "wiki_*" 2>/dev/null)
+    FILTER_OPTIONS="--save-sorted $MODEL_IN $MODEL_OUT"
 
-    # create the language model
-    echo $TRAIN_CMD --order $ORDER --max-unigrams $MAX_UNIGRAMS --language ${lang} "$MODELFILE" ${LANGDIRS} "*.txt,wiki_*"
-    $TRAIN_CMD --order $ORDER --max-unigrams $MAX_UNIGRAMS --language ${lang} "$MODELFILE" ${LANGDIRS} "*.txt,wiki_*"
+    case "$lang_id" in
+        en)
+            $FILTER_CMD \
+                -p 499,499  \
+                -r "\'s$|^[^IaA]$" \
+                -n "^\w{1}\ | \s\S{1,3}(?:\s|$)" \
+                -t \
+                -l $lang \
+                -N \
+                -x Union,Kingdom,Nations,New,Barack,Obama,Bush,South,West,North,East,Southern,Western,Northern,Eastern,Mean,Standard,Coast,Time,Grand,Central,Station,Large,Cloud,Collider,Psychology,Geographic \
+                -i 2.0 \
+                ${FILTER_OPTIONS}                
+            ;;
+
+        de)
+            Onboard/pypredict/tools/filter \
+                -p 399  \
+                -r "\'s$|^\S$" -n "^\w{1}\ | \s\S{1,3}(?:\s|$)" \
+                -t \
+                -l $lang \
+                -N \
+                -i 300.0 \
+                ${FILTER_OPTIONS}                
+            ;;
+
+        *)
+            echo "Unsupported language $lang, Aborting"
+            exit 1
+    esac
+
+    echo
+
 done
 
 
